### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by TejasAvinashShetty** [gate42qc/Guide-to-QC-and-QI#4]
Probably could make a website derived from this (well maintained) repo. Quite easy now with Github pages. I could help in some ways.
It would allow more people to discover and benefit from the information you have curated.

**Comment by jakob-avetis** [comment]
Hi Tejas, thanks for the idea and the willingness to help. Here is the website :) 
https://www.gate42.org/Guide-to-QC-and-QI/
